<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Gibbed.RED.FileFormats</RootNamespace>
    <AssemblyName>Gibbed.RED.FileFormats</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibbed.Helpers\Gibbed.Helpers.csproj" />
  </ItemGroup>
</Project>
