<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gibbed.RED.Pack</RootNamespace>
    <AssemblyName>Gibbed.RED.Pack</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibbed.Helpers\Gibbed.Helpers.csproj" />
    <ProjectReference Include="..\Gibbed.RED.FileFormats\Gibbed.RED.FileFormats.csproj" />
    <ProjectReference Include="..\NDesk.Options\NDesk.Options.csproj" />
  </ItemGroup>
</Project>
