<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Gibbed.Squish</RootNamespace>
    <AssemblyName>Gibbed.Squish</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="squish_32.dll" CopyToOutputDirectory="Always" />
    <Content Include="squish_64.dll" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
